# Generated by Django 3.2.9 on 2021-11-28 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_member',
            new_name='EventMmember',
        ),
    ]
