# Generated by Django 3.2.9 on 2021-11-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_event_member_eventmmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longitude',
            new_name='altitude',
        ),
    ]
