# Generated by Django 3.2.9 on 2021-11-28 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_rename_longitude_location_altitude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMmember',
            new_name='EventMember',
        ),
    ]
